name: Webapp CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Backend.."
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building Frontend.."
  deploy-backened-dev:
    name: Delploy Backend to Kubernetes DEV
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-dev:
    name: Delploy Frontend to Kubernetes DEV
    runs-on: ubuntu-latest
    needs: [build-frontend]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-dev:
    name: Run API Tests against DEV Backend
    runs-on: ubuntu-latest
    needs: [deploy-backened-dev]
    steps:
      - run: echo "Running tests.."
  deploy-backened-stg:
    name: Delploy Backend to Kubernetes STG
    runs-on: ubuntu-latest
    needs: [test-backend-dev]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-stg:
    name: Delploy Frontend to Kubernetes STG
    runs-on: ubuntu-latest
    needs: [deploy-frontend-dev]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-stg:
    name: Run API Tests against PRD Backend
    runs-on: ubuntu-latest
    needs: [deploy-backened-stg]
    steps:
      - run: echo "Running tests.."
  deploy-backened-prd:
    name: Delploy Backend to Kubernetes PRD
    runs-on: ubuntu-latest
    needs: [test-backend-stg]
    steps:
      - run: echo "Deploying Backend.."
  deploy-frontend-prd:
    name: Delploy Frontend to Kubernetes PRD
    runs-on: ubuntu-latest
    needs: [deploy-frontend-stg]
    steps:
      - run: echo "Deploying Frontend.."
  test-backend-prd:
    name: Run API Tests against PRD Backend
    runs-on: ubuntu-latest
    needs: [deploy-backened-prd]
    steps:
      - run: echo "Running tests.."
